#!/usr/bin/env ruby

require './lib/all'

require 'commander/import'

program :version, '0.0.1'
program :description, 'Lonely Planet Render'

command :render do |c|
  c.syntax = 'render render [options]'
  c.description = 'Render html files from dataset'
  
  c.option '-t', '--taxonomy FILE', 'Specify the path to taxonomy xml file'
  c.option '-d', '--destination FILE', 'Specify the path to destination xml file'
  c.option '--template FILE', 'Specify the template folder'
  c.option '-o', '--output PATH', 'Specify the output folder'
  c.action do |args, options|
    options.default taxonomy: 'taxonomy.xml',
                    destination: 'destination.xml',
                    template: 'lib/templates',
                    output: 'output'

    FileUtils.rm_rf(options.output)

    render = HamlRender.new  File.join(options.template, 'page.haml'), options.output
    FakeTaxonomy = Struct.new 'FakeTaxonomy', :get_path

    FileUtils.mkpath File.join(options.output, 'static')
    FileUtils.cp_r File.join(options.template, 'static/'), options.output

    render.render(FakeTaxonomy.new('page'), nil)
  end
end

command :analyze do |c|
  c.syntax = 'render analyze [FILE...]'
  c.description = 'Analyze xml semantic hierarchy'
  c.action do |args, options|
    args.each do |file|
      puts "Analyzing file #{file}..."
      SemanticNode.analyze(file).print_tree
    end
  end
end

default_command :help
